"""Verifies PQ-signed X.509 certificates without reimplementing ASN.1/DER
encoding.

Building or signing a certificate stays delegated entirely to `openssl` +
`oqs-provider` (see `test_pq_tls.py`) -- getting DER encoding subtly
wrong is exactly the kind of mistake this project has no business
risking, and `openssl`/`oqs-provider` already implement it correctly.

What this module actually does, and why each piece is safe to do
ourselves:
1. Parses certificate *structure* (subject, issuer, validity, the raw
   bytes that were signed, the raw signature) using `cryptography`'s
   X.509 parser -- it correctly parses structure even for a signature
   algorithm it doesn't recognize well enough to verify itself (verified
   this session against a real ML-DSA-65 cert and a real Falcon-512
   cert, both generated by `test_pq_tls.py`'s own openssl+oqs-provider
   setup).
2. Extracts the raw (non-DER-wrapped) public key from a certificate's
   SubjectPublicKeyInfo via a small generic DER TLV walker. This is not
   a certificate parser or encoder -- it only knows the fixed RFC 5280
   *field order* of a TBSCertificate well enough to skip to the
   SubjectPublicKeyInfo field, and that a PQ SubjectPublicKeyInfo's BIT
   STRING content IS the raw public key with no further wrapping.
3. Verifies the actual signature via src/algorithms/signature.py's
   Signature.verify() -- the same tested liboqs binding used everywhere
   else in this repo, not a new crypto implementation.

NOT AUDITED -- see the project README's disclaimer. This does NOT check
certificate chains, key usage, extensions, or revocation -- see
docs/FUTURE_DIRECTIONS.md for what a real chain verifier still needs.
"""
from datetime import datetime, timezone

from cryptography import x509

from src.algorithms.signature import Signature, SignatureError

_TAG_SEQUENCE = 0x30
_TAG_BIT_STRING = 0x03
_TAG_CONTEXT_0 = 0xA0  # [0] EXPLICIT version, present in v3 certs

# Signature algorithm OIDs observed in this project's own oqs-provider
# build this session -- NOT a general OID registry. ML-DSA's OIDs are
# NIST-assigned (FIPS 204) and should be stable across builds; Falcon's
# is an OQS-private experimental arc (1.3.9999.*) and may differ across
# oqs-provider versions -- verify against your own build before relying
# on it, the same way this mapping was verified against this one.
KNOWN_SIGNATURE_OIDS = {
    "2.16.840.1.101.3.4.3.18": "ML-DSA-65",
    "1.3.9999.3.11": "Falcon-512",
}


class PKIError(RuntimeError):
    """Raised for certificate structure or verification failures."""


def _read_tlv(data: bytes, offset: int) -> tuple:
    """Reads one definite-length DER TLV element starting at `offset`.
    Returns (tag, content_bytes, offset_of_next_element). DER always
    uses definite-length encoding, so this is sufficient for anything
    produced by openssl. Does not handle indefinite-length BER, which
    DER-conformant certificates never use."""
    if offset + 2 > len(data):
        raise PKIError("truncated DER data while reading a TLV header")
    tag = data[offset]
    length_byte = data[offset + 1]
    if length_byte & 0x80 == 0:
        length = length_byte
        content_start = offset + 2
    else:
        num_length_bytes = length_byte & 0x7F
        length = int.from_bytes(data[offset + 2:offset + 2 + num_length_bytes], "big")
        content_start = offset + 2 + num_length_bytes
    content = data[content_start:content_start + length]
    if len(content) != length:
        raise PKIError("truncated DER data: declared length exceeds available bytes")
    return tag, content, content_start + length


def load_certificate(pem_bytes: bytes) -> x509.Certificate:
    """Thin wrapper over cryptography's PEM loader, kept here so callers
    don't need to import cryptography.x509 directly for the common case."""
    try:
        return x509.load_pem_x509_certificate(pem_bytes)
    except ValueError as exc:
        raise PKIError(f"failed to parse certificate: {exc}") from exc


def algorithm_for_certificate(cert: x509.Certificate) -> str:
    """Returns the liboqs algorithm name (e.g. "ML-DSA-65") for a
    certificate's signature algorithm OID, using KNOWN_SIGNATURE_OIDS.
    Raises PKIError for any OID not in that (deliberately small,
    verified-not-guessed) table."""
    oid = cert.signature_algorithm_oid.dotted_string
    if oid not in KNOWN_SIGNATURE_OIDS:
        raise PKIError(
            f"unrecognized signature algorithm OID {oid!r} -- add it to "
            f"KNOWN_SIGNATURE_OIDS only after verifying it against your "
            f"own oqs-provider build, the way the existing entries were")
    return KNOWN_SIGNATURE_OIDS[oid]


def extract_raw_public_key(cert: x509.Certificate) -> bytes:
    """Extracts the raw public key bytes from a certificate's
    SubjectPublicKeyInfo. Works for algorithms cryptography's own
    cert.public_key() doesn't recognize (ML-DSA, Falcon here) precisely
    because it never tries to interpret the key material -- it only
    walks generic DER structure to reach the SPKI's BIT STRING payload."""
    tbs = cert.tbs_certificate_bytes
    outer_tag, tbs_fields, _ = _read_tlv(tbs, 0)
    if outer_tag != _TAG_SEQUENCE:
        raise PKIError("tbs_certificate_bytes is not a DER SEQUENCE -- unexpected cert structure")

    offset = 0
    first_tag, _, next_offset = _read_tlv(tbs_fields, offset)
    if first_tag == _TAG_CONTEXT_0:
        offset = next_offset  # skip the optional [0] version field (present in v3 certs)

    # Skip, in RFC 5280 order: serialNumber, signature AlgorithmIdentifier,
    # issuer, validity, subject -- five fields, regardless of what's
    # inside any of them, since DER TLVs are self-delimiting.
    for _ in range(5):
        _, _, offset = _read_tlv(tbs_fields, offset)

    spki_tag, spki_content, _ = _read_tlv(tbs_fields, offset)
    if spki_tag != _TAG_SEQUENCE:
        raise PKIError("expected a SubjectPublicKeyInfo SEQUENCE at this TBSCertificate field position")

    _alg_tag, _alg_content, spki_offset = _read_tlv(spki_content, 0)
    bitstring_tag, bitstring_content, _ = _read_tlv(spki_content, spki_offset)
    if bitstring_tag != _TAG_BIT_STRING:
        raise PKIError("expected a BIT STRING for subjectPublicKey")

    unused_bits = bitstring_content[0]
    if unused_bits != 0:
        raise PKIError(
            f"subjectPublicKey BIT STRING has {unused_bits} unused bits -- "
            f"not byte-aligned, unexpected for a raw PQ public key")
    return bitstring_content[1:]


def verify_certificate_signature(cert: x509.Certificate, issuer_public_key: bytes,
                                  algorithm: str) -> bool:
    """Verifies that cert's signature was made by the holder of
    issuer_public_key, using algorithm's liboqs binding. Does NOT check
    validity dates, name matching, key usage, or build a trust chain --
    see is_self_signed_and_valid() for one specific common case."""
    try:
        sig = Signature(algorithm)
    except SignatureError as exc:
        raise PKIError(f"can't verify: {exc}") from exc
    return sig.verify(issuer_public_key, cert.tbs_certificate_bytes, cert.signature)


def is_currently_valid(cert: x509.Certificate) -> bool:
    """True if `now` falls within the cert's validity period.

    The *_utc-suffixed properties were only added in cryptography 42.0;
    this project's requirements.txt allows 41.0.0+, and the much older
    system cryptography 3.4.8 (distinct from this project's own venv,
    confirmed this session) has neither the _utc properties nor a
    deprecation warning for the naive ones. Prefer _utc when available
    (silences the deprecation warning on newer installs) and fall back
    to the naive accessor (always UTC per X.509) otherwise."""
    not_before = getattr(cert, "not_valid_before_utc", None) or \
        cert.not_valid_before.replace(tzinfo=timezone.utc)
    not_after = getattr(cert, "not_valid_after_utc", None) or \
        cert.not_valid_after.replace(tzinfo=timezone.utc)
    now = datetime.now(timezone.utc)
    return not_before <= now <= not_after


def is_self_signed_and_valid(cert: x509.Certificate, algorithm: str = None) -> bool:
    """Convenience for the common case: a self-signed cert (issuer ==
    subject) whose own SubjectPublicKeyInfo is also the signing key.
    Checks the signature AND that `now` falls within the cert's validity
    period. Does not check anything else (extensions, key usage, name
    constraints, ...). If algorithm is omitted, it's looked up via
    algorithm_for_certificate()."""
    if cert.issuer != cert.subject:
        return False
    if not is_currently_valid(cert):
        return False

    if algorithm is None:
        algorithm = algorithm_for_certificate(cert)

    public_key = extract_raw_public_key(cert)
    return verify_certificate_signature(cert, public_key, algorithm)


def verify_chain(leaf: x509.Certificate, issuer: x509.Certificate,
                  leaf_algorithm: str = None) -> bool:
    """Verifies that `leaf` was signed by `issuer` (a real two-certificate
    chain step -- leaf's issuer name must match issuer's subject name,
    leaf's signature must verify against issuer's public key, and leaf
    must currently be within its validity period). Does NOT check that
    `issuer` itself is trusted/self-signed/valid, chain depth beyond one
    step, key usage (e.g. that `issuer` is actually allowed to sign
    certificates), or name constraints -- see docs/FUTURE_DIRECTIONS.md.
    Call is_self_signed_and_valid(issuer) separately to also confirm the
    root of a 2-level chain is a valid, currently-unexpired self-signed
    CA cert."""
    if leaf.issuer != issuer.subject:
        return False
    if not is_currently_valid(leaf):
        return False

    if leaf_algorithm is None:
        leaf_algorithm = algorithm_for_certificate(leaf)

    issuer_public_key = extract_raw_public_key(issuer)
    return verify_certificate_signature(leaf, issuer_public_key, leaf_algorithm)
